# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
apiVersion: v2
name: iag5
description: A Helm chart for Kubernetes
icon: https://www.itential.com/wp-content/uploads/2023/12/Product-Icon_IAG.png
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.5

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "5.1.1"

home: https://github.com/itential/iag5-helm
sources:
  - https://github.com/itential/iag5-helm

# This application has a conditional dependency on Etcd. When the application is run in a certain
# configuration this becomes a requirement.
dependencies:
  - name: etcd
    version: "^11.3.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: etcd.enabled
  - name: cert-manager
    version: "^1.12.3"
    repository: "https://charts.jetstack.io"
    condition: certManager.enabled
  - name: external-dns
    version: "^1.17.0"
    repository: "https://kubernetes-sigs.github.io/external-dns/"
    condition: external-dns.enabled
