{{- $replicaCount := .Values.runnerSettings.replicaCount | int }}
{{- if lt $replicaCount 0 }}
{{- $replicaCount = 0 }}
{{- end }}
{{/* Set TLS variables with defaults */}}
{{- $distributedExecution := "false" -}}
{{- $haEnabled := "false" -}}
{{/* Override defaults when conditions are met */}}
{{- if (.Values.runnerSettings).replicaCount -}}
  {{- $distributedExecution = "true" -}}
{{- end -}}
{{- if gt ((.Values.serverSettings).replicaCount | default 0 | int) 1 -}}
  {{- $haEnabled = "true" -}}
{{- end -}}
{{- $runnerSettings := .Values.runnerSettings | default dict -}}
{{- $runnerEnv := $runnerSettings.env | default dict -}}
{{- range $i := until $replicaCount }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iag5.fullname" $ }}-runner-{{ $i }}
  labels:
    {{- include "iag5.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "iag5.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "iag5.annotations" $ | nindent 8 }}
      {{- with $.Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: runner
        {{- include "iag5.labels" $ | nindent 8 }}
        {{- with $.Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          command:
            - "/usr/local/bin/iagctl"
            - "runner"
          env:
            # Application settings
            - name: GATEWAY_APPLICATION_MODE
              value: "runner"
            - name: GATEWAY_SECRETS_ENCRYPT_KEY_FILE
              value: "/etc/gateway/keys/encryption.key"
            - name: GATEWAY_APPLICATION_CLUSTER_ID
              value: {{ $.Values.applicationSettings.clusterId | quote }}
            - name: GATEWAY_LOG_LEVEL
              value: {{ $.Values.applicationSettings.logLevel | default "INFO" | quote }}
            - name: GATEWAY_STORE_BACKEND
              value: {{ $.Values.applicationSettings.storeBackend | default "memory" | quote }}
            {{- if eq $.Values.applicationSettings.storeBackend "etcd" }}
            - name: GATEWAY_STORE_ETCD_HOSTS
              value: {{ $.Values.applicationSettings.etcdHosts | quote }}
            - name: GATEWAY_STORE_ETCD_USE_TLS
              value: {{ $.Values.applicationSettings.etcdUseTLS | default "false" | quote }}
            - name: GATEWAY_STORE_ETCD_CLIENT_CERT_AUTH
              value: {{ $.Values.applicationSettings.etcdUseClientCertAuth | default "false" | quote }}
            {{- if $.Values.applicationSettings.etcdUseTLS }}
            - name: GATEWAY_STORE_ETCD_CA_CERTIFICATE_FILE
              value: "/etc/ssl/etcd/ca.crt"
            - name: GATEWAY_STORE_ETCD_CERTIFICATE_FILE
              value: "/etc/ssl/etcd/tls.crt"
            - name: GATEWAY_STORE_ETCD_PRIVATE_KEY_FILE
              value: "/etc/ssl/etcd/tls.key"
            {{- end }}
            {{- end }}
            {{- if eq $.Values.applicationSettings.storeBackend "dynamodb" }}
            - name: GATEWAY_STORE_DYNAMODB_TABLE_NAME
              value: {{ $.Values.applicationSettings.dynamodbTableName | quote }}
            {{- end }}
            {{- range $key, $value := $.Values.applicationSettings.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            # Runner mode settings
            {{- if not $.Values.runnerSettings.env.GATEWAY_RUNNER_LISTEN_ADDRESS }}
            - name: GATEWAY_RUNNER_LISTEN_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- end }}
            - name: GATEWAY_RUNNER_USE_TLS
              value: {{ $.Values.useTLS | default "false" | quote }}
            {{- if $.Values.useTLS }}
            - name: GATEWAY_APPLICATION_CA_CERTIFICATE_FILE
              value: "/etc/ssl/gateway/ca.crt"
            - name: GATEWAY_RUNNER_CERTIFICATE_FILE
              value: "/etc/ssl/gateway/tls.crt"
            - name: GATEWAY_RUNNER_PRIVATE_KEY_FILE
              value: "/etc/ssl/gateway/tls.key"
            {{- end }}
            {{/* Announce the service address to match the DNS names in the TLS certs */}}
            - name: GATEWAY_RUNNER_ANNOUNCEMENT_ADDRESS
              value: "{{ $.Values.service.name }}-runner-{{ $i }}.{{ $.Release.Namespace }}.svc.cluster.local"
            {{- range $key, $value := $.Values.runnerSettings.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if eq $.Values.applicationSettings.storeBackend "dynamodb" }}
          envFrom:
            - secretRef:
                name: dynamodb-aws-secrets
          {{- end }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: runner-port
              containerPort: {{ $.Values.port }}
              protocol: TCP
          {{- if $.Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml $.Values.livenessProbe.settings | nindent 12 }}
          {{- end }}
          {{- if $.Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml $.Values.readinessProbe.settings | nindent 12 }}
          {{- end }}
          {{- if $.Values.resources.enabled }}
          resources:
            {{- toYaml $.Values.resources.runners | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: gateway-secrets-volume
              mountPath: /etc/gateway/keys/encryption.key
              subPath: gatewayEncryptionKey
              readOnly: true
          {{- if $.Values.useTLS }}
            - name: gateway-cert-volume
              mountPath: /etc/ssl/gateway
              readOnly: true
          {{- end }}
          {{- if and (eq $.Values.applicationSettings.storeBackend "etcd") $.Values.applicationSettings.etcdUseTLS }}
            - name: etcd-client-certs
              mountPath: /etc/ssl/etcd
              readOnly: true
          {{- end }}
          {{- with $.Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: gateway-secrets-volume
          secret:
            secretName: itential-gateway-secrets
      {{- if $.Values.useTLS }}
        - name: gateway-cert-volume
          secret:
            secretName: {{ include "iag5.fullname" $ }}-tls-secret
      {{- end }}
      {{- if and (eq $.Values.applicationSettings.storeBackend "etcd") $.Values.applicationSettings.etcdUseTLS }}
        - name: etcd-client-certs
          secret:
            secretName: etcd-client-certs
      {{- end }}
      {{- with $.Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
